### ISSUE TITLE
`node-lmdb` error invalid ELF header

### ISSUE THREAD

**Issue by dangell7** [HotPocketDev/evernode-sdk#43]
I wanted to try to use [lmdb](https://github.com/Venemo/node-lmdb) however I have run into an issue. 

The error I receive is:

```
node:internal/modules/cjs/loader:1185
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /hpdevkit_vol/node1/contract_fs/mnt/rw/state/prebuilds/darwin-x64/node.abi93.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.31 (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:615:18)
    at __nccwpck_require__ (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:790:42)
    at Object.878 (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:628:14)
    at __nccwpck_require__ (/hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:790:42)
    at /hpdevkit_vol/node1/contract_fs/mnt/rw/state/index.js:839:23 {
  code: 'ERR_DLOPEN_FAILED'
}
```

Any suggestions? I also tried using this [lmdb](https://github.com/kriszyp/lmdb-js) but received this error when building:

```
Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js):
UnhandledSchemeError: Reading from "bun:ffi" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "bun:" URIs.
    at /Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:461251
    at Hook.eval [as callAsync] (eval at create (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:72685)
    at Object.processResource (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:461176)
    at processResource (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:612888)
    at iteratePitchingLoaders (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:612247)
    at iteratePitchingLoaders (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:612344)
    at /Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:612476
    at handleResult (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:617642)
    at loadLoader (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:617181)
    at /Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1770552
    at /Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:374702
    at _done (eval at create (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:9:1)
    at eval (eval at create (/Users/denisangell/projects/transia-rnd/evernode/daocontract/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:34:22)
```

**Comment by dangell7** [comment]
I found the issue and we may want to note this down for the future...

To recreate the issue create a fresh contract. 

Then install lmdb with `npm install node-lmdb`. Then require lmdb in the contract file. `const lmdb = require('node-lmdb');`

Now, when you go to build the dist, you will notice a new folder, `prebuilds` with `darwinx86`. You will also notice the export in the `index.js` file `module.exports = require(__nccwpck_require__.ab + "prebuilds/darwin-x64/node.abi83.node");`

What you need to do to solve the issue is 

1. delete the prebuilds directory in the dist folder. Copy the `node_modules/node-lmdb/prebuilds` and paste in the dist directory. 
2. update the export in the index.js file to use `linux-x64`

**Comment by dangell7** [comment]
Basically its building on my mac, for darwin but the docker image is not darwin. I think that was the issue. 

Its not a great solve because I cannot build the index again or it will overwrite my changes.

**Comment by dangell7** [comment]
I fixed the error for `lmdb-js` as well. The build error for webpack. I needed to adjust the build script and add `-e lmdb` to ignore the package because its a node package not a web package.
